### ISSUE TITLE
Outdated Mods folder

### ISSUE THREAD

**Issue by VivianVanilla** [Jedilloyd/SpeedstersHero#1]
# Outdated Mods
### Requesting an update of the latest mods folder so that my version may be compatible with the server.
@Jedilloyd Seems that the latest commit has not included the latest addition of **mods**.

**Comment by Jedilloyd** [comment]
Hey I'm so sorry about your issue it seems like I forgot to publish the latest mods if you check again everything should be up to date with the server!
